title: Valley Clock Works 
description: Landing page for Tell City Clock Shop Valley Clock Works
sitename: Valley Clock Works
baseurl: '/valleyclockworks'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
